x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100M

services:
  server:
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    image: judge0/judge0:1.13.1
    volumes:
      - /box:/box
      - ./judge0.conf:/judge0.conf:ro
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        bind:
          propagation: rshared
    ports:
      - "2358:2358"
    privileged: true
    <<: *default-logging
    restart: always

  workers:
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    volumes:
      - /box:/box
      - ./judge0.conf:/judge0.conf:ro
      - type: bind
        source: /sys/fs/cgroup
        target: /sys/fs/cgroup
        bind:
          propagation: rshared
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    <<: *default-logging
    restart: always

volumes:
  data:
