
x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: "100m"

volumes:
  data:

services:
  server:
    image: judge0/judge0:1.13.1
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    privileged: true
    pid: "host"
    security_opt:
      - apparmor=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /box:/box
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "2358:2358"
    restart: always

  workers:
    image: judge0/judge0:1.13.1
    command: ["./scripts/workers"]
    cap_add:
      - SYS_ADMIN
      - SYS_RESOURCE
    privileged: true
    pid: "host"
    security_opt:
      - apparmor=unconfined
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      - /box:/box
      - ./judge0.conf:/judge0.conf:ro
    restart: always

  db:
    image: postgres:16.2
    env_file: judge0.conf
    volumes:
      - data:/var/lib/postgresql/data/
    <<: *default-logging
    restart: always

  redis:
    image: redis:7.2.4
    command: >
      bash -c 'docker-entrypoint.sh --appendonly no --requirepass "$$REDIS_PASSWORD"'
    env_file: judge0.conf
    <<: *default-logging
    restart: always
